server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jasper9797/spring-cloud-config-store-demo
          search-paths:
           - '*service'



